package com.net.response;
import java.io.Serializable;

// THIS CODE IS GENERATED BY unknown, DO NOT EDIT

public final class LoginResponse implements Serializable {
    public String mobile;
    public String identifyCode;
    public boolean hasToken;


    public void setMobile (String mobile) {
         this.mobile = mobile;
    }

    public String getMobile (String mobile) {
         return mobile;
    }

    public void setIdentifyCode (String identifyCode) {
         this.identifyCode = identifyCode;
    }

    public String getIdentifyCode (String identifyCode) {
         return identifyCode;
    }

    public void setHasToken (boolean hasToken) {
        this.hasToken = hasToken;
    }

    public boolean isHasToken (boolean hasToken) {
         return hasToken;
    }


    @Override
    public String toString() {
         return "LoginResponse{"+
                 "mobile='" + mobile + '\''+
                 ",identifyCode='" + identifyCode + '\''+
                 ",hasToken='" + hasToken + '\''+
         '}';
    }

}