package com.saic.network.model.response;
import java.io.Serializable;

// THIS CODE IS GENERATED BY unknown, DO NOT EDIT

public final class LoginResponse implements Serializable {
    public String accessToken;
    public String uid;
    public boolean realNameCertificated;
    public boolean nameMobileBinded;
    public boolean registration;
    public String imToken;

    public void setAccessToken (String accessToken) {
         this.accessToken = accessToken;
    }

    public String getAccessToken (String accessToken) {
         return accessToken;
    }

    public void setUid (String uid) {
         this.uid = uid;
    }

    public String getUid (String uid) {
         return uid;
    }

    public void setRealNameCertificated (boolean realNameCertificated) {
        this.realNameCertificated = realNameCertificated;
    }

    public boolean isRealNameCertificated (boolean realNameCertificated) {
         return realNameCertificated;
    }

    public void setNameMobileBinded (boolean nameMobileBinded) {
        this.nameMobileBinded = nameMobileBinded;
    }

    public boolean isNameMobileBinded (boolean nameMobileBinded) {
         return nameMobileBinded;
    }

    public void setRegistration (boolean registration) {
        this.registration = registration;
    }

    public boolean isRegistration (boolean registration) {
         return registration;
    }

    public void setImToken (String imToken) {
         this.imToken = imToken;
    }

    public String getImToken (String imToken) {
         return imToken;
    }

    @Override
    public String toString() {
         return "LoginResponse{"+
                 "accessToken='" + accessToken + '\''+
                 ",uid='" + uid + '\''+
                 ",realNameCertificated='" + realNameCertificated + '\''+
                 ",nameMobileBinded='" + nameMobileBinded + '\''+
                 ",registration='" + registration + '\''+
                 ",imToken='" + imToken + '\''+
                 '}';
    }

}