package com.saic.network.model.request;

// THIS CODE IS GENERATED BY unknown, DO NOT EDIT

public final class LoginRequest {

    public String mobile;
    public String identifyCode;

    public LoginRequest (String mobile,String identifyCode) {
        this.mobile = mobile;
        this.identifyCode = identifyCode;
    }
}