<#assign toBindType = {"Boolean":"Long", "Byte":"Long", "Short":"Long", "Int":"Long", "Long":"Long", "Float":"Double", "Double":"Double", "String":"String", "ByteArray":"Blob" }/>
<#assign toCursorType = {"Boolean":"Short", "Byte":"Short", "Short":"Short", "Int":"Int", "Long":"Long", "Float":"Float", "Double":"Double", "String":"String", "ByteArray":"Blob" }/>
<#assign complexTypes = ["String", "ByteArray", "Date"]/>
package ${model.javaPackageName};

// THIS CODE IS GENERATED BY unknown, DO NOT EDIT

public final class ${model.className} {

<#list model.propertyList as property>
    public ${property.key} ${property.value};
</#list>

    public ${model.className} (<#list model.propertyList as property>${property.key} ${property.value}<#if property_has_next>,</#if></#list>) {
    <#list model.propertyList as property>
        this.${property.value} = ${property.value};
    </#list>
    }


}