<#assign toBindType = {"Boolean":"Long", "Byte":"Long", "Short":"Long", "Int":"Long", "Long":"Long", "Float":"Double", "Double":"Double", "String":"String", "ByteArray":"Blob" }/>
<#assign toCursorType = {"Boolean":"Short", "Byte":"Short", "Short":"Short", "Int":"Int", "Long":"Long", "Float":"Float", "Double":"Double", "String":"String", "ByteArray":"Blob" }/>
<#assign complexTypes = ["String", "ByteArray", "Date"]/>
package ${entity.javaPackageName};

// THIS CODE IS GENERATED BY unknown, DO NOT EDIT

import com.saic.network.demo.model.request.LoginRequest;
import com.saic.network.demo.constant.AppUrl;
import com.saic.network.demo.model.response.R_CommonResource;
import com.saic.network.demo.model.response.R_DriverActivate;
import com.saic.network.demo.model.response.R_Login;
import com.saic.network.demo.model.response.R_ModeStatus;
import com.saic.network.demo.model.response.R_UploadFile;
import com.saic.network.http.SCHttpCallback;
import com.saic.network.http.SCHttpRequest;
import com.saic.network.http.SCRequestAccessory;
import com.saic.network.http.SCRequestMethod;
import com.saic.network.http.SCRequestWrapper;
import com.saic.network.http.model.SCBaseResponse;
import java.io.File;

import io.reactivex.disposables.Disposable;
import okhttp3.MediaType;
public final class RequestFactory {
<#list entity.propertyList as property>
    public ${property.key} ${property.value};
</#list>

    public ${entity.className} (<#list entity.propertyList as property>${property.key} ${property.value}<#if property_has_next>,</#if></#list>) {
    <#list entity.propertyList as property>
        this.${property.value} = ${property.value};
    </#list>

    }
}